--========================================================================================================================
-- LocalizedText
--========================================================================================================================
INSERT OR REPLACE INTO BaseGameText
		(Tag,					Text)
VALUES
--========================================================================================================================
-- ETHIOPIA
--========================================================================================================================
		("LOC_CIVILIZATION_SUK_ETHIOPIA_NAME",  
		"Ethiopia"	),
		("LOC_CIVILIZATION_SUK_ETHIOPIA_DESCRIPTION",  
		"Ethiopian Empire"	),
		("LOC_CIVILIZATION_SUK_ETHIOPIA_ADJECTIVE",  
		"Ethiopia"	),
		-- RWF
		("LOC_CIVILIZATION_SUK_ETHIOPIA_DESCRIPTION_JFD_CIVILIZATION",
		"Ethiopian Civilization"),		
--------------------------------------------------------------------
-- UA
--------------------------------------------------------------------
		("LOC_TRAIT_CIVILIZATION_SUK_SOLOMONIC_DYNASTY_NAME",  
		"Solomonic Dynasty"	),
		("LOC_TRAIT_CIVILIZATION_SUK_SOLOMONIC_DYNASTY_DESCRIPTION",  
		"May purchase Settlers, Builders, and Traders with [ICON_Faith] Faith. City Centers and Holy Sites yield +2 [ICON_Faith] Faith when built on a Hills tile."), 
--------------------------------------------------------------------
-- Cities
--------------------------------------------------------------------
		("LOC_CITY_NAME_ETHIOPIA_ADDIS_ABABA",
		"Addis Ababa"),	
		("LOC_CITY_NAME_ETHIOPIA_AXUM",
		"Axum"),	
		("LOC_CITY_NAME_ETHIOPIA_LALIBELA",
		"Lalibela"),	
		("LOC_CITY_NAME_ETHIOPIA_GONDAR",
		"Gondar"),	
		("LOC_CITY_NAME_ETHIOPIA_DEBRE_BERHAN",
		"Debre Berhan"),	
		("LOC_CITY_NAME_ETHIOPIA_HARAR",
		"Harar"),	
		("LOC_CITY_NAME_ETHIOPIA_DIRE_DAWA",
		"Dire Dawa"),	
		("LOC_CITY_NAME_ETHIOPIA_ADWA",
		"Adwa"),	
		("LOC_CITY_NAME_ETHIOPIA_BAHIR_DAR",
		"Bahir Dar"),	
		("LOC_CITY_NAME_ETHIOPIA_ADAMA",
		"Adama"),	
		("LOC_CITY_NAME_ETHIOPIA_MEKELE",
		"Mek’ele"),	
		("LOC_CITY_NAME_ETHIOPIA_ADULIS",
		"Adulis"),	
		("LOC_CITY_NAME_ETHIOPIA_AWASA",
		"Awasa"),	
		("LOC_CITY_NAME_ETHIOPIA_JIMMA",
		"Jimma"),	
		("LOC_CITY_NAME_ETHIOPIA_JIJIGA",
		"Jijiga"),	
		("LOC_CITY_NAME_ETHIOPIA_DESSIE",
		"Dessie"),	
		("LOC_CITY_NAME_ETHIOPIA_SHASHAMANE",
		"Shashamane"),	
		("LOC_CITY_NAME_ETHIOPIA_DEBRE_ZEYIT",
		"Debre Zeyit"),	
		("LOC_CITY_NAME_ETHIOPIA_HOSAENA",
		"Hosaena"),	
		("LOC_CITY_NAME_ETHIOPIA_SODO",
		"Sodo"),	
		("LOC_CITY_NAME_ETHIOPIA_ASELLA",
		"Asella"),	
		("LOC_CITY_NAME_ETHIOPIA_NEKEMTE",
		"Nekemte"),	
		("LOC_CITY_NAME_ETHIOPIA_DILA",
		"Dila"),	
		("LOC_CITY_NAME_ETHIOPIA_ADIGRAT",
		"Adigrat"),	
		("LOC_CITY_NAME_ETHIOPIA_DEBRE_MARKOS",
		"Debre Markos"),	
		("LOC_CITY_NAME_ETHIOPIA_DEBRE_TABOR",
		"Debre Tabor"),	
		("LOC_CITY_NAME_ETHIOPIA_SHIRE",
		"Shire"),	
		("LOC_CITY_NAME_ETHIOPIA_SEBETA",
		"Sebeta"),	
		("LOC_CITY_NAME_ETHIOPIA_AMBO",
		"Ambo"),	
		("LOC_CITY_NAME_ETHIOPIA_NEGELE_ARSI",
		"Negele Arsi"),	
		("LOC_CITY_NAME_ETHIOPIA_GAMBELA",
		"Gambela"),	
		("LOC_CITY_NAME_ETHIOPIA_ZIWAY",
		"Ziway"),	
		("LOC_CITY_NAME_ETHIOPIA_WELDIYA",
		"Weldiya"),	
		("LOC_CITY_NAME_ETHIOPIA_KOMBOLCHA",
		"Kombolcha"),	
		("LOC_CITY_NAME_ETHIOPIA_ASAITA",
		"Asaita"),	
		("LOC_CITY_NAME_ETHIOPIA_DELGHI",
		"Delghi"),	
		("LOC_CITY_NAME_ETHIOPIA_ADDIS_ZEMEN",
		"Addis Zemen"),	
		("LOC_CITY_NAME_ETHIOPIA_DEBRE_WERQ",
		"Debre Werq"),	
		("LOC_CITY_NAME_ETHIOPIA_DEJEN",
		"Dejen"),	
		("LOC_CITY_NAME_ETHIOPIA_ARBOYE",
		"Arboye"),	
		("LOC_CITY_NAME_ETHIOPIA_BICHENA",
		"Bichena"),	
		("LOC_CITY_NAME_ETHIOPIA_BATI",
		"Bati"),	
		("LOC_CITY_NAME_ETHIOPIA_DABAT",
		"Dabat"),	
		("LOC_CITY_NAME_ETHIOPIA_MOJO",
		"Mojo"),	
		("LOC_CITY_NAME_ETHIOPIA_NEGASH",
		"Negash"),	
		("LOC_CITY_NAME_ETHIOPIA_KOBO",
		"Kobo"),	
		("LOC_CITY_NAME_ETHIOPIA_DANGILA",
		"Dangila"),	
		("LOC_CITY_NAME_ETHIOPIA_GORGORA",
		"Gorgora"),	
		("LOC_CITY_NAME_ETHIOPIA_CHENCHA",
		"Chencha"),	
		("LOC_CITY_NAME_ETHIOPIA_GELEMSO",
		"Gelemso"),	
		("LOC_CITY_NAME_ETHIOPIA_SOKORU",
		"Sokoru"),	
		("LOC_CITY_NAME_ETHIOPIA_IRGALEM",
		"Irgalem"),	
		("LOC_CITY_NAME_ETHIOPIA_KEBRI_MANGEST",
		"Kebri Mangest"),	
		("LOC_CITY_NAME_ETHIOPIA_DEBRE_MARQOS",
		"Debre Marqos"),	
		("LOC_CITY_NAME_ETHIOPIA_FINOTE_SELAM",
		"Finote Selam"),	
		("LOC_CITY_NAME_ETHIOPIA_MOTA",
		"Mota"),	
		("LOC_CITY_NAME_ETHIOPIA_KONSO",
		"Konso"),
--------------------------------------------------------------------
-- Citizens
--------------------------------------------------------------------
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_1",
		"Zoskales"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_2",
		"Datawnas"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_3",
		"Aphilas"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_4",
		"Gersem"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_5",
		"Ousanas"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_6",
		"Eon"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_7",
		"Tazena"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_8",
		"Wazena"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_9",
		"Beygat"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MALE_10",
		"Sahama"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_1",
		"Gudit"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_2",
		"Makeda"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_3",
		"Berhane"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_4",
		"Masoba"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_5",
		"Bilén Saba"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_6",
		"Berhane"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_7",
		"Abebech"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_8",
		"Merima"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_9",
		"Mare"),
		("LOC_CITIZEN_SUK_ETHIOPIA_FEMALE_10",
		"Amane"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_1",
		"Yohannes"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_2",
		"Dawit"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_3",
		"Yaqob"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_4",
		"Tewodros"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_5",
		"Eskender"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_6",
		"Andreyas"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_7",
		"Gelawdewos"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_8",
		"Giyorgis"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_9",
		"Salomon"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_MALE_10",
		"Mikael"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_1",
		"Maryam"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_2",
		"Yohanna"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_3",
		"Tereza"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_4",
		"Eleni"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_5",
		"Abebech"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_6",
		"Senedu"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_7",
		"Hibret"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_8",
		"Tirunesh"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_9",
		"Dina"),
		("LOC_CITIZEN_SUK_ETHIOPIA_MODERN_FEMALE_10",
		"Israela"),
--------------------------------------------------------------------
-- Named Places
--------------------------------------------------------------------
		("LOC_NAMED_RIVER_TEKEZE_NAME",						"Tekezé River"),
		("LOC_NAMED_RIVER_OMO_NAME",						"Omo River"),
		("LOC_NAMED_RIVER_BARO_NAME",						"Baro River"),
		("LOC_NAMED_RIVER_AWASH_NAME",						"Awash River"),
		("LOC_NAMED_RIVER_SHEBELLE_NAME",					"Shebelle River"),
		("LOC_NAMED_RIVER_ANGEREB_NAME",					"Angereb River"),
		("LOC_NAMED_RIVER_GANALE_DORIA_NAME",				"Ganale Doria River"),
		("LOC_NAMED_RIVER_ABAY_NAME",						"Abay River"),
		("LOC_NAMED_RIVER_LESSER_ABAY_NAME",				"Lesser Abay River"),
		("LOC_NAMED_RIVER_DAWA_NAME",						"Dawa River"),
		("LOC_NAMED_RIVER_WEYIB_NAME",						"Weyib River"),
		
		("LOC_NAMED_MOUNTAIN_ETHIOPIAN_HIGHLANDS_NAME",		"Ethiopian Highlands"),
		("LOC_NAMED_MOUNTAIN_SEMIEN‎_NAME",					"Semien Mountains‎"),
		("LOC_NAMED_MOUNTAIN_BALE‎_NAME",					"Bale Mountains‎"),
		("LOC_NAMED_MOUNTAIN_AHMAR_NAME",					"Ahmar Mountains"),
		("LOC_NAMED_MOUNTAIN_AMARO_NAME",					"Amaro Mountains"),
		("LOC_NAMED_MOUNTAIN_ENTOTO_NAME",					"Entoto Mountains"),
		("LOC_NAMED_MOUNTAIN_DANAKIL_ALPS_NAME",			"Danakil Alps"),

		("LOC_NAMED_VOLCANO_FENTALE_NAME",					"Mount Fentale"),
		("LOC_NAMED_VOLCANO_DABBAHU_NAME",					"Dabbahu Volcano"),
		("LOC_NAMED_VOLCANO_ALE_BAGU_NAME",					"Ale Bagu"),
		("LOC_NAMED_VOLCANO_AFDERA_NAME",					"Afderà Volcano"),
		("LOC_NAMED_VOLCANO_ALAYTA_NAME",					"Mount Alayta"),
		("LOC_NAMED_VOLCANO_AYALU_NAME",					"Mount Ayalu"),
		("LOC_NAMED_VOLCANO_GADA_ALE_NAME",					"Gada Ale"),
		("LOC_NAMED_VOLCANO_BORALE_ALE_NAME",				"Borale Ale"),
		("LOC_NAMED_VOLCANO_ASAVYO_NAME",					"Asavyo Volcano"),
		("LOC_NAMED_VOLCANO_BORAWLI_NAME",					"Borawli Volcano"),
		("LOC_NAMED_VOLCANO_ADWA_NAME",						"Adwa Volcano"),
		("LOC_NAMED_VOLCANO_TAT_ALI_NAME",					"Tat Ali"),
		("LOC_NAMED_VOLCANO_HAYLI_GUBBI_NAME",				"Hayli Gubbi"),
		("LOC_NAMED_VOLCANO_ASAVYO_NAME",					"Asavyo Volcano"),
		("LOC_NAMED_VOLCANO_WONCHI_NAME",					"Wonchi Volcano"),

		("LOC_NAMED_LAKE_ABAYA_NAME",						"Lake Abaya"),
		("LOC_NAMED_LAKE_ZWAY_NAME",						"Lake Zway"),
		("LOC_NAMED_LAKE_CHEW_BAHIR_NAME",					"Lake Chew Bahir"),
		("LOC_NAMED_LAKE_SHALA_NAME",						"Lake Shala"),
		("LOC_NAMED_LAKE_ABBE_NAME",						"Lake Abbe"),
		("LOC_NAMED_LAKE_CHAMO_NAME",						"Lake Chamo"),
		("LOC_NAMED_LAKE_LANGANO_NAME",						"Lake Langano"),
		("LOC_NAMED_LAKE_ABIJATTA_NAME",					"Lake Abijatta"),
		("LOC_NAMED_LAKE_HASHENGE_NAME",					"Lake Hashenge"),
		("LOC_NAMED_LAKE_HAYQ_NAME",						"Lake Hayq"),

		("LOC_NAMED_SEA_GULF_OF_ZULA_NAME",					"Gulf of Zula"),
		("LOC_NAMED_SEA_BAY_OF_BEYLUL_NAME",				"Bay of Beylul"),
		("LOC_NAMED_SEA_BAY_OF_HAWAKIL_NAME",				"Bay of Hawakil"),
		("LOC_NAMED_SEA_BAY_OF_ANFILE_NAME",				"Bay of Anfile"),
--------------------------------------------------------------------
-- Info
--------------------------------------------------------------------
		("LOC_CIVINFO_SUK_ETHIOPIA_LOCATION",
		"Africa"),
		("LOC_CIVINFO_SUK_ETHIOPIA_SIZE",
		"Est. 426 thousand square miles (1,104.3 thousand square km)"),
		("LOC_CIVINFO_SUK_ETHIOPIA_POPULATION",
		"99.4 million (2015 est.)"),
		("LOC_CIVINFO_SUK_ETHIOPIA_CAPITAL",
		"Various, with an iterant court in the Medieval period, but most prominently Axum, Lalibela, Gondar, and currently Addis Ababa."),
--------------------------------------------------------------------
-- Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_1",
		"Home to ancient empires dating back to the waning centuries of the first millennium BC, Ethiopia has a storied history driven by the rule of great kings and emperors. As one of the few African nations to avoid the colonial ambitions of Europe, Ethiopia maintained its sovereignty into the 21st century, only briefly coming under Italian occupation for 8 years during WWII and its prelude."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_2",
		"Ethiopia, Africa's tenth largest nation, covers the majority of the Horn of Africa, nestled along the continent's northeastern coast. Bisected by the Great Rift Valley, Ethiopia's geography is dominated by highly elevated plateaus and disjointed mountain ranges. Sitting atop the African tectonic plate, which has been in the process of splitting apart for millions of years, Ethiopia has found itself on the receiving end of frequent earthquakes throughout history. The country is also home to several dozen active and dormant volcanoes, including Erta Ale, one of the few volcanoes in the world with an ever-present lake of lava on its summit. The climate of Ethiopia varies greatly, although the nation as a whole is part of a tropical zone with heavy rainfall during the summer monsoon season followed by a dry, moderate winter."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_3",
		"As the most advanced of the early Ethiopian kingdoms, the powerful Axumite Empire is well documented in history, but also steeped in legend. Founded in roughly the 4th century BC, Axum grew to become a powerful center of trade over the next five hundred years. The valuable commodities of frankincense and myrrh, harvested from trees prevalent in Ethiopia, brought great wealth to the city of Axum and its people. Through the exportation of these goods, plus lucrative trades in ivory and various precious metals, Axum became an integral part of the trade routes connecting Egypt, Rome, and India, enough so to facilitate the minting of currency within Axum to support the flourishing local economy."),
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_4",
		"Christianity was introduced into the country by Frumentius, who was consecrated first bishop of Ethiopia by Saint Athanasius of Alexandria about 330. Frumentius converted Ezana, who left several inscriptions detailing his reign both before and after his conversion. One inscription found at Axum, states that he conquered the nation of the Bogos, and returned thanks to his father, the god Mars, for his victory. Later inscriptions show Ezana's growing attachment to Christianity, and Ezana's coins bear this out, shifting from a design with disc and crescent to a design with a cross. Expeditions by Ezana into the Kingdom of Kush at Meroe in Sudan may have brought about its demise, though there is evidence that the kingdom was experiencing a period of decline beforehand. As a result of Ezana's expansions, Aksum bordered the Roman province of Egypt."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_5",
		"However, after centuries of prosperity, legends say the expansive empire's downfall came at the hands of a rebellious queen named Gudit. As the story goes, Axum had long been a stronghold of Christianity, and the Jewish queen Gudit sought the throne by way of conquest, purportedly devastating the countryside before murdering the royal family of Axum. Although the story of Gudit's life and brief reign is mysterious and controversial, it can be said with certainty that the decline of Axum did coincide with her speculated arrival in the 10th century AD."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_6",
		"The Zagwe Dynasty, established in the early 12th century after the fall of Axum, was the first dynasty of the Ethiopian Empire, which would control the nation well into the 20th century. Although the Zagwe Dynasty was only in power for little more than a century, they contributed greatly to the spread of Christianity throughout Ethiopia, which would play a major role in the future of the country."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_7",
		"In 1270 AD, the monarchy that would control Ethiopia for the coming centuries arose under the leadership of Emperor Yekuno Amlak, founder of the Solomonic Dynasty. The rulers of the Solomonic Dynasty attributed their lineage to the great biblical king Solomon and his queen, Makeda. As legend has it, in the 10th century BC, Queen Makeda travelled from her kingdom in Sheba (thought to have formed part of modern Ethiopia) to Israel in an effort to learn from the wisdom of revered king Solomon. Although accounts differ as to her relationship with Solomon, Makeda later gave birth to a son, Menelik. Said to have been educated in the court of Solomon before returning to Ethiopia, Menelik brought with him the legendary Ark of the Covenant as a gift from Solomon. Ruling sometime around 950 BC, Menelik I was the originator of the biblical ancestry held sacred by later Emperors of Ethiopia."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_8",
		"Nearly 2,000 years after the reign of Menelik, Yekuno Amlak claimed to have traced his ancestry through a long line of relatives to establish a clear connection to the legendary emperor and his parents. This newly formed Solomonic Dynasty maintained its rule over Ethiopia for more than five centuries, lasting until the reign of Haile Selassie in the 1970s. Fully supported by the influential Ethiopian Orthodox Church (which to this day still claims to be holding the legendary Ark of the Covenant), the Solomonic emperors enjoyed relative stability during their reign, despite several attempted incursions from outside the country."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_9",
		"During the mid-16th century, Ethiopia was bordered by the increasingly powerful Islamic Kingdom of Adal, led by Imam Ahmad Gargn, known colloquially as ""The Conqueror."" Initiating a holy war against the Christians of Ethiopia in 1529, Imam Ahmad spurred the great conflict that came to be known as the Ethiopian-Adal War. As battles raged for nearly 15 years, Ahmad was nearly successful in wiping out the entire kingdom, laying claim to vast swaths of Ethiopian territory."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_10",
		"After suffering such great losses, the Ethiopian Empire was forced to call on the assistance of Portuguese reinforcements to help in repelling the Islamic armies. Explorers and missionaries from Portugal had reached Ethiopia in the prior decades, intent on converting the populace to Roman Catholicism, and were fighting a war of their own against the Islamic Ottomans. After a prolonged conflict that eventually drew the Ottomans in to aid the Adals, the war was settled in 1543 following the deaths of both Imam Ahmad and the Portuguese general Cristovao da Gama. Ethiopia was left to recover from the war, but the rapid spread of Catholicism in the surrounding regions led to internal strife as the Ethiopian Orthodox Church struggled to maintain a firm grip on the nation."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_11",
		"The following period is known as the Zamana Mesafent, or ""Age of Princes"". Occuring in the 18th century, this period was marked by near constant turmoil within Ethiopia. The development of opposing religious factions, along with constant regional disputes, led to the collapse of central government control. As battles erupted between the princes, warlords, and nobility, each attempting to divide the region and increase their own power, the common people of Ethiopia were forced to endure the ravages of these futile conflicts."),			
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_12",
		"The Emperor who finally brought an end to the Age of Princes, Kassa Hailu, first gained notoriety as an outlaw and highwayman. Assembling an army and amassing great wealth through his smuggling operations, Kassa Hailu gained popular support by sharing his riches with the poor. After uniting several of the decentralized provinces and gaining a strong following, Hailu was eventually crowned as Emperor Twedoros II in 1855. Following his coronation, Ethiopia as a whole stabilized, and his reign is considered by many to mark the beginnings of modern Ethiopia."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_13",
		"Ethiopia was never colonized by a European power, and the highlight of Ethiopia's stuggle to maintain its sovereignty during the colonial period is the reign of Menelik II. Emperor Menelik II reigned from 1889 to 1913, fending off the encroachment of European powers. Italy posed the greatest threat, having begun to colonize part of what would become its future colony of Eritrea in the mid 1880s. In 1896 Ethiopia defeated Italy at the Battle of Adwa, which remains famous today as the first victory of an African nation over a colonial power."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_14",
		"Perhaps the best remembered of Ethiopia's great emperors, Haile Selassie, ascended the throne in 1930 and quickly gained recognition throughout the world for Ethiopia and its people. During his reign he made a strong push for the abolition of slavery, a prospect that had been suggested, but never fulfilled, by his many predecessors. Emperor Selassie was also deeply concerned with modernizing his nation and ending many of the feudal policies that still held sway in Ethiopia."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_15",
		"In 1935, the Fascist Italian regime led by Benito Mussolini invaded Ethiopia in an attempt to claim the territory as a province of Italy. Facing a superior military force, Ethiopia was unable to repel the invasion, and by 1936, Mussolini had declared the establishment of an Italian Empire including the occupied Ethiopian territory. During this period, Haile Selassie was forced into exile, taking refuge in Great Britain throughout the occupation. Selassie made his case for the defense of Ethiopia to the League of Nations, including a stern reproach of Italy's use of mustard gas against Ethiopian soldiers and citizens alike. Despite his plea, international assistance was not forthcoming, and years passed before the British East African Campaign of World War II was successful in ending the Italian occupation. Haile Selassie returned to his throne as Emperor of Ethiopia following Italy's defeat, and he would rule successfully for nearly 40 years before the arrival of a new threat."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_16",
		"In 1974, a Communist-led military coup resulted in Haile Selassie's removal from power and imprisonment within the royal palace. The group deposing him, known as the Derg, formed the Provisional Military Government of Socialist Ethiopia and ruled with an iron fist. Selassie died mysteriously while imprisoned, a controversial subject that continues to stir debate today. As the Derg and their communist ideals were not universally supported, their military coup also marked the beginning of the Ethiopian Civil War. This great conflict claimed the lives of several hundred thousand innocent bystanders as fighting continued for over 15 years. In 1991, the Ethiopian People's Revolutionary Democratic Front was finally successful in overthrowing the government, leading to the creation of a new constitution and a democratically elected government."),	
		("LOC_PEDIA_CIVILIZATIONS_PAGE_CIVILIZATION_SUK_ETHIOPIA_CHAPTER_HISTORY_PARA_17",
		"Known today as the Federal Democratic Republic of Ethiopia, the nation faces a number of major socio-economic issues as the second most populous country in Africa. The wide-ranging geographic isolation facing some groups within the country has made it increasingly difficult to provide education, healthcare, and, in many cases, the basic necessities of life. Although the nation currently holds multiparty elections, corruption within the government is a constant concern, and crackdowns in recent years have led to international condemnation over the killing of protesters and opposition party members."),	
--========================================================================================================================
-- Shotelai
--========================================================================================================================
		("LOC_UNIT_SUK_SHOTELAI_NAME",  
		"Shotelai"	),
		("LOC_UNIT_SUK_SHOTELAI_DESCRIPTION",  
		"Ethiopian unique Medieval Era unit that replaces the Pikeman. +5 [ICON_Strength] Combat Strength against melee units. +1 XP per turn while garrisoned in a City Center. An extra +1 XP per turn for cities founded on a Hills tile, and +1 XP per turn if that city is the [ICON_Capital] Capital."),
		("LOC_PEDIA_UNITS_PAGE_UNIT_SUK_SHOTELAI_CHAPTER_HISTORY_PARA_1",  
		"The shotel is a thin, broadly circular bladed sword originating in Ethiopia. Shotelai fought exclusively with the shotel, using the blade's shape to strike around their opponent's shields, penetrating their defences and hitting them in key areas; the kidneys or the lungs were common targets. The blade on a shotel differed from that of a shamshir or a kopesh as it was nearly a full semicircle, making it more awkward for the user to wield. In the hands of an experienced swordsman, however, its potential for death was magnified. Evidence for the shotel dates from the earliest Damotians (Damites) and Axumites, used by both mounted and dismounted warriors. After the Solomonic restoration of Atse Yikuno Amlak I, the resurgent Emperors began to re-establish the Axumite armies. This culminated in the reign of Amda Seyon I. Ethiopian forces were armed with short and long swords such as the Seif and Gorade."),			

		("LOC_ABILITY_SUK_SHOTELAI_MELEE_NAME",  
		"Anti-Melee"	),
		("LOC_ABILITY_SUK_SHOTELAI_MELEE_DESCRIPTION",  
		"+5 [ICON_Strength] Combat Strength against melee units (Shotelai)."),
		("LOC_ABILITY_SUK_SHOTELAI_MELEE_MODIFIER_DESCRIPTION",  
		"+{Amount} [ICON_Strength] Combat Strength vs. melee units."),

		("LOC_ABILITY_SUK_SHOTELAI_XP_NAME",  
		"Blessing of Saint George"	),
		("LOC_ABILITY_SUK_SHOTELAI_XP_DESCRIPTION",  
		"+1 XP per turn while garrisoned in a City Center. An extra +1 XP per turn for cities founded on a Hills tile, and +1 XP per turn if that city is the [ICON_Capital] Capital."),
--========================================================================================================================
-- Rock-Hewn Church
--========================================================================================================================
		("LOC_BUILDING_SUK_ROCK_HEWN_CHURCH_NAME",  
		"Rock-Hewn Church"	),
		("LOC_BUILDING_SUK_ROCK_HEWN_CHURCH_DESCRIPTION",  
		"A building unique to Ethiopia. Required to purchase Apostles and Inquisitors with [ICON_Faith] Faith. +3 [ICON_Production] Production, this bonus increases to +5 [ICON_Production] Production if this district has a Worship Building. +1 [ICON_GreatEngineer] Great Engineer point."),
		("LOC_PEDIA_BUILDINGS_PAGE_BUILDING_SUK_ROCK_HEWN_CHURCH_CHAPTER_HISTORY_PARA_1",  
		"Ethiopia's conversion to Christianity fundamentally changed its history, and this is perhaps best evidenced by the country's rock-hewn churches. The very landscape of the country was transformed as the faithful cut thousands of churches from the living rock. The most remarkable and renowned example of these rock-cut churches is the pilgrimage site of Lalibela, in the Tigray mountains, dated to the thirteenth century. The wondrous accomplishment of that cluster of eleven structures excavated from the tufa, envisioned as a New Jerusalem and credited to the labors of angels, required an architectural genius capable of conceptualizing before work began every aspect of the design, from its interior spaces to exterior details."),		
--========================================================================================================================
-- Zara Yaqob
--========================================================================================================================
		("LOC_LEADER_SUK_ZARAYAQOB_NAME",  
		"Zara Yaqob"	),
--------------------------------------------------------------------
-- ULA
--------------------------------------------------------------------
		("LOC_TRAIT_LEADER_SUK_DEBRE_MITMAQ_NAME",  
		"Council of Debre Mitmaq"	),
		("LOC_TRAIT_LEADER_SUK_DEBRE_MITMAQ_DESCRIPTION",  
		"Receive an extra Wildcard policy slot when you have 3 or more Holy Site Districts. Receive a second Wildcard policy slot if you have 6 or more Holy Site Districts."), 
--------------------------------------------------------------------
-- Agenda
--------------------------------------------------------------------
		("LOC_AGENDA_SUK_BOOK_OF_LIGHT_NAME",  
		"Book of Light"	),
		("LOC_AGENDA_SUK_BOOK_OF_LIGHT_DESCRIPTION",  
		"Likes civilizations from different continents who share his faith. Is wary of civilizations from his home continent that follow a different religion."	),

		("LOC_DIPLO_KUDO_LEADER_SUK_ZARAYAQOB_REASON_ANY",  
		"(You are on a different continent, but follow the same faith.)"	),
		("LOC_DIPLO_MODIFIER_SUK_BOOK_OF_LIGHT_SAME_RELIGION",  
		"Zara Yaqob is pleased to see his religion flourishing so far away"	),

		("LOC_DIPLO_WARNING_LEADER_SUK_ZARAYAQOB_REASON_ANY",  
		"(You are on the same continent, but follow a different faith.)"	),
		("LOC_DIPLO_MODIFIER_SUK_BOOK_OF_LIGHT_DIFF_RELIGION",  
		"Zara Yaqob is upset that your nation is near him, but haven't converted"	),
--------------------------------------------------------------------
-- RWF Support
--------------------------------------------------------------------
		("LOC_GOVERNMENT_JFD_CHIEFDOM_LEADER_TITLE_SUK_ZARAYAQOB",
		"Alek’a"),
		("LOC_GOVERNMENT_JFD_AUTOCRACY_LEADER_TITLE_SUK_ZARAYAQOB",
		"Ras"),
		("LOC_GOVERNMENT_JFD_OLIGARCHY_LEADER_TITLE_SUK_ZARAYAQOB",
		"Ras"),
		("LOC_GOVERNMENT_JFD_MONARCHY_LEADER_TITLE_SUK_ZARAYAQOB",
		"Negus"),
		("LOC_GOVERNMENT_JFD_NOBLE_REPUBLIC_LEADER_TITLE_SUK_ZARAYAQOB",
		"Reise Mekwanint"),
		("LOC_GOVERNMENT_JFD_EMPIRE_LEADER_TITLE_SUK_ZARAYAQOB",
		"Negusa Nagast"),																
--------------------------------------------------------------------------------------------------------------------------
-- Loading Screen
--------------------------------------------------------------------------------------------------------------------------
		("LOC_LOADING_INFO_LEADER_SUK_ZARAYAQOB",
		"It is the Lord's will that guides your hand, pious Emperor Zara Yaqob. Make your empire a bastion for the faithful, building great churches across the land, and watch as your people's faith brings them to glory. Rule wisely, and let Ethiopia be a Mount of Light, shining as a beacon for all the world."  	),
--------------------------------------------------------------------------------------------------------------------------
-- Diplo
--------------------------------------------------------------------------------------------------------------------------
-- First Meet
-------------------------------------
		("LOC_DIPLO_FIRST_MEET_LEADER_SUK_ZARAYAQOB_ANY",
		"I am the Emperor Constantine I of Ethiopia, though perhaps you know me as Zara Yaqob. I welcome you to my most holy empire."),
		("LOC_DIPLO_FIRST_MEET_VISIT_RECIPIENT_LEADER_SUK_ZARAYAQOB_ANY",
		"People are always astounded by our churches. The city nearby has a few, I invite you to visit."),
		("LOC_DIPLO_FIRST_MEET_NEAR_INITIATOR_POSITIVE_LEADER_SUK_ZARAYAQOB_ANY",
		"I gladly accept."),
		("LOC_DIPLO_FIRST_MEET_NO_MANS_INFO_EXCHANGE_LEADER_SUK_ZARAYAQOB_ANY",
		"I founded Debre Berhan at the Lord's behest. What of your capital?"),
-------------------------------------
-- Agenda Diplo
-------------------------------------
		("LOC_DIPLO_KUDO_EXIT_LEADER_SUK_ZARAYAQOB_ANY",
		"Truly, it is gratifying to see our faith spread so far!"),
		("LOC_DIPLO_WARNING_EXIT_LEADER_SUK_ZARAYAQOB_ANY",
		"I cannot feel comfortable with heathens so close. I pray you will find the light."),
-------------------------------------
-- War and Peace
-------------------------------------
	-- Human Declares War
		("LOC_DIPLO_DECLARE_WAR_FROM_HUMAN_LEADER_SUK_ZARAYAQOB_ANY",
		"We are blessed by the saints! Ethiopia shall not fail!"),
	-- AI Declares War
		("LOC_DIPLO_DECLARE_WAR_FROM_AI_LEADER_SUK_ZARAYAQOB_ANY",
		"Your blasphemous words leave me no choice. I hereby declare war."),
	-- Making Peace
		("LOC_DIPLO_MAKE_PEACE_AI_ACCEPT_DEAL_LEADER_SUK_ZARAYAQOB_ANY",
		"Well fought. We have both earned this peace."),
		("LOC_DIPLO_MAKE_PEACE_AI_REFUSE_DEAL_LEADER_SUK_ZARAYAQOB_ANY",
		"No. I cannot accept."),
		("LOC_DIPLO_MAKE_PEACE_FROM_AI_LEADER_SUK_ZARAYAQOB_ANY",
		"For the sake of our peoples, I beg you to end this war."),
	-- Defeat
		("LOC_DIPLO_DEFEAT_FROM_AI_LEADER_SUK_ZARAYAQOB_ANY",
		"If Ethiopia falls, then it is no doubt God's will. I pray you be merciful."),
-------------------------------------
-- DoF
-------------------------------------
		("LOC_DIPLO_DECLARE_FRIEND_FROM_AI_LEADER_SUK_ZARAYAQOB_ANY",
		"Ethiopia is a stronghold of the faith, and perhaps you are too. Will you join me in friendship?"),
	-- AI requested friendship
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_ZARAYAQOB_ANY",
		"Wonderful. May our friendship be blessed by all the Saints."),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_AI_LEADER_SUK_ZARAYAQOB_ANY",
		"A shame. But if it is not part of God's plan, it will not come to pass."),
	-- On human requests friendship
		("LOC_DIPLO_ACCEPT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_ZARAYAQOB_ANY",
		"I accept. The Lord wills it."),
		("LOC_DIPLO_REJECT_DECLARE_FRIEND_FROM_HUMAN_LEADER_SUK_ZARAYAQOB_ANY",
		"I will not be inclined to agree until I am convinced of your devotion to God. No."),
-------------------------------------
-- Delegation
-------------------------------------
		("LOC_DIPLO_DELEGATION_FROM_AI_LEADER_SUK_ZARAYAQOB_ANY",
		"I have sent a delegation with dabo kolo and coffee. Please, enjoy."),
		("LOC_DIPLO_ACCEPT_DELEGATION_FROM_HUMAN_LEADER_SUK_ZARAYAQOB_ANY",
		"Your delegation has arrived. I thank you sincerely for the gifts."),
		("LOC_DIPLO_REJECT_DELEGATION_FROM_HUMAN_LEADER_SUK_ZARAYAQOB_ANY",
		"The Lord has given us many gifts. We have no need for your trinkets."),
-------------------------------------
-- Denounce
-------------------------------------
		("LOC_DIPLO_DENOUNCE_FROM_HUMAN_LEADER_SUK_ZARAYAQOB_ANY",
		"Why would I care for the words of a heretic? Your words are naught but wind."),
		("LOC_DIPLO_DENOUNCE_FROM_AI_LEADER_SUK_ZARAYAQOB_ANY",
		"Blasphemers like you are a stain upon the earth."),
-------------------------------------
-- Alliance
-------------------------------------
		("LOC_DIPLO_MAKE_ALLIANCE_FROM_AI_LEADER_SUK_ZARAYAQOB_ANY",
		"Our successes make it clear that our partnership has been blessed by God. Let us cement and declare our friendship to the world with an alliance!"),
-------------------------------------
-- Misc Standard Lines
-------------------------------------
		("LOC_DIPLO_GREETING_LEADER_SUK_ZARAYAQOB_ANY",
		"Welcome."),
		("LOC_DIPLO_REJECT_MAKE_DEAL_FROM_AI_LEADER_SUK_ZARAYAQOB_ANY",
		"As a servant of God, I cannot agree."),
		("LOC_DIPLO_ACCEPT_MAKE_DEAL_FROM_AI_LEADER_SUK_ZARAYAQOB_ANY",
		"Praise the Lord! This is excellent."),
		("LOC_DIPLO_OPEN_BORDERS_FROM_AI_LEADER_SUK_ZARAYAQOB_ANY",
		"I beg you permit my people, servants of the Lord, to pass through your lands."),
		("LOC_DIPLO_ACCEPT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_ZARAYAQOB_ANY",
		"You may pass through Ethiopia, with my blessing. Godspeed."),
		("LOC_DIPLO_REJECT_OPEN_BORDERS_FROM_HUMAN_LEADER_SUK_ZARAYAQOB_ANY",
		"I cannot allow heathens and heretics enter Ethiopia. I am sorry."),
		("LOC_DIPLO_WARNING_TOO_MANY_TROOPS_NEAR_ME_LEADER_SUK_ZARAYAQOB_ANY",
		"If you are trying to intimidate us with your army, it’s not working. Move them, or face the consequences."),
--------------------------------------------------------------------
-- Quote and Pedia
--------------------------------------------------------------------
		("LOC_PEDIA_LEADERS_PAGE_SUK_ZARAYAQOB_QUOTE",  
		"Do not weep O’ Christian people, and do not feel afflicted because the monastery of Mitmaq in Egypt has been destroyed. We will build here a church to Our Holy Virgin Mary and will call it Debre Mitmaq."  	),
		("LOC_PEDIA_LEADERS_PAGE_SUK_ZARAYAQOB_TITLE",
		"Zara Yaqob"),
		("LOC_PEDIA_LEADERS_PAGE_SUK_ZARAYAQOB_SUBTITLE",
		"Negusa Nagast of Ethiopia"),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_ZARAYAQOB_CHAPTER_CAPSULE_BODY",
		"Ethiopia is a paragon of religious and architectural prowess. Zara Yaqob provides in invaluable administrative touch once the ball starts rolling."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_ZARAYAQOB_CHAPTER_DETAILED_BODY",
		"Ethiopia has multiple incentives to prioritise [ICON_Faith] Faith generation, most prominently the ability to utilise your surplus [ICON_Faith] Faith to expand and grow. Good Holy Site district placement also will provide a nice production bonus with the Rock-Hewn Church, so place them well. You will want to place many of them in fact, because with enough Holy Site districts, you will earn additional Wildcard policy slots from Zara Yaqob's ability."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_ZARAYAQOB_CHAPTER_HISTORY_PARA_1",
		"Zara Yaqob was Emperor of Ethiopia from 1434 until 1468. A member of the Solomonic Dynasty, which traced its heritage back to the Biblical King Solomon, Zara Yaqob was an extremely devout, if occasionally draconian, ruler. Confined to the Amba Geshen prison for the early years of his life due to being a potential threat to his brother Tewodros's grip on the throne, Zara Yaqob only gained monarchal power in 1434 after his brother's death."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_ZARAYAQOB_CHAPTER_HISTORY_PARA_2",
		"At the time Zara Yaqob assumed the throne, the Ethiopian church had been divided over the issue of Biblical Sabbath observance for roughly a century. One group, loyal to the Coptic bishops, believed that the day of rest should be observed only on Sunday, or Great Sabbath; another group, the followers of Ewostatewos, believed with their founder that both the original seventh-day Sabbath (i.e., Saturday, or Lesser Sabbath) and Sunday should be observed."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_ZARAYAQOB_CHAPTER_HISTORY_PARA_3",
		"He was successful in persuading two recently arrived Egyptian bishops, Mikael and Gabriel, into accepting a compromise aimed at restoring harmony with the House of Ewostatewos, as the followers of Ewostatewos were known. At the same time, he made efforts to pacify the House of Ewostatewos. While the Ewostathians were won over to the compromise by 1442, the two bishops only agreed to the compromise at the Council of Debre Mitmaq in Tegulet ."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_ZARAYAQOB_CHAPTER_HISTORY_PARA_4",
		"Emperor Zara Yaqob also continued as the defender of the Patriarch of Alexandria. When he heard in 1441 of the destruction of the Egyptian monastery of Debre Mitmaq by Sultan Az-Zahir Sayf-ad-Din Jaqmaq, he called for a period of mourning, then sent a letter of strong protest to the Sultan. He reminded Jaqmaq that he had Muslim subjects whom he treated fairly, and warned that he had the power to divert the Nile, but refrained from doing so for the human suffering it would cause. Jaqmaq responded with gifts to appease Zara Yaqob's anger, but refused to rebuild the Coptic Churches he had destroyed."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_ZARAYAQOB_CHAPTER_HISTORY_PARA_5",
		"Zara Yaqob sent delegates to the Council of Florence in 1441, and established ties with the papacy and Western Christianity. They were confused when council prelates insisted on calling their monarch Prester John. They tried to explain that nowhere in Zara Yaqob's list of regnal names did that title occur. However, the delegates' admonitions did little to stop Europeans from referring to the monarch as their mythical Christian king, Prester John."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_ZARAYAQOB_CHAPTER_HISTORY_PARA_6",
		"Zara Yaqob was strict in his religious beliefs. Citizens who did not rigidly follow the prescripts of the Christian Church and adorn themselves with religious markings were put to death. If a person admitted to, or was accused of, worshipping the devil (or another non-Christian god), they were put to death. Even Zara Yaqob's own family was not sheltered from these punishments. Several were beaten and put to death, including his own wife, in an effort to give credibility to his harsh punishments, which were widely criticized."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_ZARAYAQOB_CHAPTER_HISTORY_PARA_7",
		"After a conspiracy organized by one of his subordinates came to light early in his reign, Zara Yaqob started exhibiting signs of paranoia. He began replacing all of his higher officials with female family members whom he felt he could trust. The emperor eventually attempted to appoint his own sisters, daughters and nieces to various governorships. Due to this paranoia, Zara Yaqob's reign is distinguished as being uniquely female dominated in a time when men traditionally held the majority of social power."),
		("LOC_PEDIA_LEADERS_PAGE_LEADER_SUK_ZARAYAQOB_CHAPTER_HISTORY_PARA_8",
		"Known mostly for his draconian religious laws, Zara Yaqob nonetheless was a practical leader and managed to protect Ethiopian interests from outside influence for the duration of his reign. Several of his progressive writings on religion, including the Mashafa Berha (The Book of Light) and the Mashafa Milad (The Book of Nativity), are still available today.");
--------------------------------------------------------------------
--------------------------------------------------------------------